services:
  test1:
    build:
     context: .
    container_name: app
    environment: 
    - ENV_TYPE=${ENV_TYPE}
    command: ["npx", "cypress", "run", "--spec", "cypress/e2e/1-getting-started/todo.cy.js"]
    volumes:
      - .:/app
  test2:
    build:
     context: .
    container_name: app2
    environment: 
    - ENV_TYPE=${ENV_TYPE}
    command: ["npx", "cypress", "run", "--spec", "cypress/e2e/2-advanced-examples/actions.cy.js"]
    volumes:
     - .:/app